# BLOQUE 1

In [2]:
import pandas as pd
import numpy as np 

print(pd.__version__)

3.0.2

In [3]:
datos_de_ejemplo = {
    "candidatos_id": [1, 2, 3],
    "nombre": ["Valentina Prieto", "Pepito Mendieta", "Carlos Lopez"],
    "ciudad": ["Bogotá", "Medellin", "Cali"]
}

df_ejm = pd.DataFrame(datos_de_ejemplo)

df_ejm

   candidatos_id            nombre    ciudad
0              1  Valentina Prieto    Bogotá
1              2   Pepito Mendieta  Medellin
2              3      Carlos Lopez      Cali

In [4]:
print(df_ejm.shape)
df_ejm.columns.to_list()

(3, 3)

['candidatos_id', 'nombre', 'ciudad']

In [ ]:
# esto genera error de lectura porqu su codificacion es diferente a la esperada
df_ejm1 = pd.read_csv("candidatos.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 137: invalid continuation byte

In [8]:
# la forma ideal seria declarando las reglas que se debe seguir

df_candidatos = pd.read_csv(
    "candidatos.csv",
    sep = ";",
    encoding= "latin-1",
    parse_dates=["fecha_registro"],
    dayfirst=True
)

df_candidatos.head(5)

,candidato_id,nombre,ciudad,departamento,nivel_ingles,tecnologia_principal,salario_esperado,fecha_registro,activo
0,1,Valentina Torres,Bogotá,Cundinamarca,Avanzado,Python,4500000.0,2024-01-15,True
1,2,Camilo Ríos,Medellín,Antioquia,Intermedio,JavaScript,3800000.0,2024-01-22,True
2,3,Laura Méndez,Cali,Valle del Cauca,Básico,NaN,5200000.0,2024-01-30,False
3,4,Andrés Guzmán,Bogotá,Cundinamarca,Avanzado,Python,6100000.0,2024-02-05,True
4,5,Daniela Ospina,Barranquilla,Atlántico,Intermedio,Java,NaN,2024-02-12,True

In [10]:
# nos da la tupla, es decir cuantas filas y columnas llenas hay 
print(df_candidatos.shape)

print(df_candidatos.dtypes)

df_candidatos.info()

(20, 9)
candidato_id                     int64
nombre                             str
ciudad                             str
departamento                       str
nivel_ingles                       str
tecnologia_principal               str
salario_esperado               float64
fecha_registro          datetime64[us]
activo                            bool
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   candidato_id          20 non-null     int64
 1   nombre                20 non-null     str
 2   ciudad                20 non-null     str
 3   departamento          20 non-null     str
 4   nivel_ingles          20 non-null     str
 5   tecnologia_principal  17 non-null     str
 6   salario_esperado      17 non-null     float64
 7   fecha_registro        20 non-null     datetime64[us]
 8   activo                20 non-null     bool
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 1.4 KB

In [12]:
print(df_candidatos["nombre"])
print(df_candidatos.ciudad)

0          Valentina Torres
1               Camilo Ríos
2              Laura Méndez
3             Andrés Guzmán
4            Daniela Ospina
5             Felipe Moreno
6          María José Parra
7          Sebastián Vargas
8             Carolina Díaz
9        Juan Pablo Herrera
10    Luisa Fernanda Castro
11          Nicolás Ramírez
12          Alejandra Muñoz
13             David Lozano
14           Natalia Suárez
15          Esteban Jiménez
16           Paula Restrepo
17           Tomás Guerrero
18          Isabella Molina
19            Mateo Salcedo
Name: nombre, dtype: str
0           Bogotá
1         Medellín
2             Cali
3           Bogotá
4     Barranquilla
5         Medellín
6           Bogotá
7      Bucaramanga
8             Cali
9           Bogotá
10        Medellín
11         Pereira
12          Bogotá
13       Cartagena
14       Manizales
15          Bogotá
16        Medellín
17            Cali
18          Bogotá
19        Medellín
Name: ciudad, dtype: str

In [15]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [16]:
df_empresas_activas = pd.read_excel(
    "empresas.xlsx",
    sheet_name="activas",
    parse_dates=["fecha_alianza"]
)
df_empresas_activas.head()

,empresa_id,nombre_empresa,sector,ciudad,tamaño,presupuesto_salario_max,fecha_alianza
0,101,TechColombia SAS,Tecnología,Bogotá,Startup,8000000,2023-06-01
1,102,DataFlow Analytics,Tecnología,Medellín,PYME,7500000,2023-08-15
2,103,Innovación Digital,Tecnología,Bogotá,Corporación,12000000,2023-09-01
3,104,Fintech Andina,Finanzas,Bogotá,PYME,9000000,2023-10-20
4,105,CloudServ Latam,Tecnología,Cali,Startup,6500000,2023-11-05

In [20]:
df_empresas_inactivas = pd.read_excel(
    "empresas.xlsx",
    sheet_name="inactivas",
    parse_dates=["fecha_alianza"]
)
df_empresas_inactivas.head()

,empresa_id,nombre_empresa,sector,ciudad,tamaño,presupuesto_salario_max,fecha_alianza
0,201,RetailCo Bogotá,Retail,Bogotá,Corporación,6000000,2022-11-01
1,202,Construcciones Tech,Construcción,Medellín,PYME,5500000,2022-12-15
2,203,Turismo Digital,Turismo,Cartagena,Startup,4500000,2023-01-10
3,204,MediaCo,Medios,Bogotá,Corporación,7000000,2023-03-22
4,205,BancaDigital SA,Finanzas,Bogotá,Corporación,10000000,2023-05-30

In [22]:
df_empresas = pd.read_excel(
    "empresas.xlsx",
    sheet_name=None,
    parse_dates=["fecha_alianza"]
)
df_empresas

{'activas':    empresa_id      nombre_empresa         sector        ciudad       tamaño  \
 0         101    TechColombia SAS     Tecnología        Bogotá      Startup
 1         102  DataFlow Analytics     Tecnología      Medellín         PYME
 2         103  Innovación Digital     Tecnología        Bogotá  Corporación
 3         104      Fintech Andina       Finanzas        Bogotá         PYME
 4         105     CloudServ Latam     Tecnología          Cali      Startup
 5         106    Salud Digital CO          Salud      Medellín         PYME
 6         107    EduTech Colombia      Educación        Bogotá      Startup
 7         108     Logística Smart      Logística  Barranquilla  Corporación
 8         109            AgriData  Agroindustria          Cali         PYME
 9         110         CiberSegura     Tecnología        Bogotá      Startup

    presupuesto_salario_max fecha_alianza
 0                  8000000    2023-06-01
 1                  7500000    2023-08-15
 2                 12000000    2023-09-01
 3                  9000000    2023-10-20
 4                  6500000    2023-11-05
 5                  7000000    2024-01-10
 6                  5500000    2024-02-14
 7                  8500000    2024-03-01
 8                  6000000    2024-03-20
 9                  9500000    2024-04-01  ,
 'inactivas':    empresa_id       nombre_empresa        sector     ciudad       tamaño  \
 0         201      RetailCo Bogotá        Retail     Bogotá  Corporación
 1         202  Construcciones Tech  Construcción   Medellín         PYME
 2         203      Turismo Digital       Turismo  Cartagena      Startup
 3         204              MediaCo        Medios     Bogotá  Corporación
 4         205      BancaDigital SA      Finanzas     Bogotá  Corporación

    presupuesto_salario_max fecha_alianza
 0                  6000000    2022-11-01
 1                  5500000    2022-12-15
 2                  4500000    2023-01-10
 3                  7000000    2023-03-22
 4                 10000000    2023-05-30  }

In [23]:
# JSON

df_postulaciones = pd.read_json("postulaciones.json")
df_postulaciones.head()

,postulacion_id,candidato_id,empresa_id,fecha_postulacion,estado,puntaje_match
0,1001,1,101,2024-02-01,Seleccionado,92.5
1,1002,2,103,2024-02-05,Pendiente,78.0
2,1003,4,101,2024-02-10,Seleccionado,95.1
3,1004,6,107,2024-02-15,Rechazado,61.3
4,1005,7,102,2024-02-20,Seleccionado,88.7

In [24]:
import sqlite3
conexion = sqlite3.connect("datajobs.db")

In [27]:
query_1 = """
    SELECT 
        candidato_id, 
        tecnologia, 
        salario_actual 
    FROM historial_salarios
    WHERE salario_actual > 3000000
    ORDER BY candidato_id DESC;
"""
df_salarios = pd.read_sql(query_1, conexion)
df_salarios.head()

df_salarios.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   candidato_id    12 non-null     int64
 1   tecnologia      12 non-null     str
 2   salario_actual  12 non-null     int64
dtypes: int64(2), str(1)
memory usage: 420.0 bytes

fillna---rellena con datos

dropna---elimina

In [31]:
print(df_candidatos.isna().head())
print(df_candidatos.isna().sum())

total_filas = len(df_candidatos)

porct_nulos = (df_candidatos.isna().sum()/ total_filas) * 100
print(porct_nulos)

   candidato_id  nombre  ciudad  departamento  nivel_ingles  \
0         False   False   False         False         False
1         False   False   False         False         False
2         False   False   False         False         False
3         False   False   False         False         False
4         False   False   False         False         False

   tecnologia_principal  salario_esperado  fecha_registro  activo
0                 False             False           False   False
1                 False             False           False   False
2                  True             False           False   False
3                 False             False           False   False
4                 False              True           False   False
candidato_id            0
nombre                  0
ciudad                  0
departamento            0
nivel_ingles            0
tecnologia_principal    3
salario_esperado        3
fecha_registro          0
activo                  0
dtype: int64
candidato_id             0.0
nombre                   0.0
ciudad                   0.0
departamento             0.0
nivel_ingles             0.0
tecnologia_principal    15.0
salario_esperado        15.0
fecha_registro           0.0
activo                   0.0
dtype: float64

In [33]:
# rellenando los nulos

tc_comun = df_candidatos["tecnologia_principal"].mode()[0]
print(tc_comun)

Python

In [34]:
df_candidatosNuevo = df_candidatos.copy()

In [36]:
df_candidatosNuevo["tecnologia_principal"].fillna(tc_comun)

0           Python
1       JavaScript
2           Python
3           Python
4             Java
5            React
6     Data Science
7           Python
8           Python
9           DevOps
10      JavaScript
11            Java
12          Python
13           React
14          Python
15    Data Science
16          DevOps
17      JavaScript
18          Python
19            Java
Name: tecnologia_principal, dtype: str

In [37]:
df_candidatosNuevo["tecnologia_principal"].isna().sum()

np.int64(3)